// Temporary file with updated models 7-14 data structure

const models7to14 = [
    {
        id: 7,
        name: "Clara",
        surname: "Becker",
        stageName: "Alpine",
        stageNameRU: "Alpine",
        country: "Germany",
        countryRU: "Германия",
        hairColor: "Blonde, wavy, shoulder-length",
        hairColorRU: "Блондинка, волнистые, до плеч",
        skinColor: "Fair",
        skinColorRU: "Светлая",
        age: 22,
        height: 176,
        bodyType: "Slim",
        bodyTypeRU: "Стройная",
        measurements: "91/59/87",
        clothingSize: "XS",
        shoeSize: "38",
        features: "High cheekbones",
        featuresRU: "Высокие скулы",
        style: "Scandinavian minimalism",
        styleRU: "Скандинавский минимализм",
        category: "artistic",
        hobbies: "Cycling, interior design",
        hobbiesRU: "Велоспорт, дизайн интерьеров",
        faceStyle: "Scandinavian style, light eyebrows",
        faceStyleRU: "Скандинавский стиль, светлые брови",
        sexualPreferences: "Heterosexual",
        sexualPreferencesRU: "Гетеросексуальная",
        created: "yes",
        social: { 
            instagram: 'https://www.instagram.com/claraalpinebecker', 
            facebook: '', 
            x: 'https://x.com/claraalpinebeck', 
            youtube: '', 
            dropbox: '', 
            website: '', 
            onlyfans: 'https://onlyfans.com/claraalpinebecker', 
            linkme: 'https://link.me/claraalpinebecker' 
        },
        bioEN: `From Munich, Clara Mist represents the harmony of Scandinavian minimalism and German precision. Passionate about cycling through the Alps, she also designs modern interiors in her free time. Her high cheekbones and serene aura make her a muse for minimalist fashion brands. She believes in beauty through simplicity.`,
        bioRU: `Родом из Мюнхена, Клара Мист сочетает скандинавский минимализм и немецкую точность. Она увлекается велопоездками по Альпам и создаёт современные интерьеры в свободное время. Высокие скулы и спокойное излучение сделали её музой для брендов минимализма. Она верит в красоту через простоту.`,
        avatar: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    },
    {
        id: 8,
        name: "Olivia",
        surname: "Rossi",
        stageName: "Shine",
        stageNameRU: "Shine",
        country: "Italy",
        countryRU: "Италия",
        hairColor: "Black, glossy",
        hairColorRU: "Чёрные, блестящие",
        skinColor: "Light olive",
        skinColorRU: "Светлая оливковая",
        age: 28,
        height: 171,
        bodyType: "Athletic",
        bodyTypeRU: "Атлетическая",
        measurements: "84/61/89",
        clothingSize: "M",
        shoeSize: "39",
        features: "Shoulder tattoo",
        featuresRU: "Татуировка на плече",
        style: "Elegant, haute couture",
        styleRU: "Изысканный, высокая мода",
        category: "fitness",
        hobbies: "Winemaking, painting",
        hobbiesRU: "Виноделие, живопись",
        faceStyle: "Elegant style, expressive eyes",
        faceStyleRU: "Изысканный стиль, выразительные глаза",
        sexualPreferences: "Heterosexual",
        sexualPreferencesRU: "Гетеросексуальная",
        created: "yes",
        social: { 
            instagram: 'https://www.instagram.com/oliviashinerossi/', 
            facebook: '', 
            x: 'https://x.com/rossi_oliv35230', 
            youtube: '', 
            dropbox: '', 
            website: '', 
            onlyfans: 'https://onlyfans.com/oliviashinerossi', 
            linkme: 'https://link.me/oliviashinerossi' 
        },
        bioEN: `Olivia Shine was born in Florence, the cradle of Renaissance art. She studied painting before turning to fashion, carrying elegance from canvas to runway. Her tattoo on the shoulder symbolizes strength and independence. Known for her refined style, she is often the face of Italian haute couture.`,
        bioRU: `Оливия Шайн родилась во Флоренции, колыбели искусства Ренессанса. Она изучала живопись, прежде чем прийти в моду, перенося элегантность с холста на подиум. Татуировка на плече символизирует силу и независимость. Её изысканный стиль сделал её лицом итальянской высокой моды.`,
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    }
];

export { models7to14 };